# Generated by Django 2.2.16 on 2022-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221130_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_djangoadmin',
            field=models.BooleanField(default=False),
        ),
    ]
